targets:
  $default:
    builders:
      freezed:
        options:
          field_rename: snake
      json_serializable:
        options:
          field_rename: snake
          explicit_to_json: true
