name: technq
description: "Sample SPK Rekomentasi Fakultas Teknik dan Informatika Di UPGRIS bagi Siswa Kelas XII SMA & SMK Mengunakan Metode AHP."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_decision_making: ^1.0.4
  firebase_core: ^3.13.1
  firebase_crashlytics: ^4.3.6
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
#  google_sign_in: ^6.3.0
#  firebase_storage: ^12.4.6
  flutter_bloc: ^9.1.1
  go_router: ^15.1.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1
  flutter_bounceable: ^1.2.0
  fluttertoast: ^8.2.12
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  loader_overlay: ^5.0.0
  shimmer: ^3.0.0
  uuid: ^4.5.1
  flutter_native_splash: ^2.4.6
  freezed_annotation: ^2.4.4
  carousel_slider: ^5.1.1
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  device_preview: ^1.2.0
#  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  injectable_generator: ^2.7.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/animation/
    - assets/json/
