// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLnB0dpCxObS9H6FbANVIYNQAu5U4ezd8',
    appId: '1:710172613282:web:02938c38dd8b81d08fd5fb',
    messagingSenderId: '710172613282',
    projectId: 'technq-dev',
    authDomain: 'technq-dev.firebaseapp.com',
    storageBucket: 'technq-dev.firebasestorage.app',
    measurementId: 'G-MXCZ1TT95P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiEFSkcJ2Arm8sM0Z1oC2yzP7SemBz37k',
    appId: '1:710172613282:android:f97d4da44f4f95378fd5fb',
    messagingSenderId: '710172613282',
    projectId: 'technq-dev',
    storageBucket: 'technq-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD7CYeNALjxKySS5CaUXFBvNTJ8Ffoil0',
    appId: '1:710172613282:ios:fb149022818fbcc28fd5fb',
    messagingSenderId: '710172613282',
    projectId: 'technq-dev',
    storageBucket: 'technq-dev.firebasestorage.app',
    iosBundleId: 'com.spk.ahp.technq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD7CYeNALjxKySS5CaUXFBvNTJ8Ffoil0',
    appId: '1:710172613282:ios:fb149022818fbcc28fd5fb',
    messagingSenderId: '710172613282',
    projectId: 'technq-dev',
    storageBucket: 'technq-dev.firebasestorage.app',
    iosBundleId: 'com.spk.ahp.technq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLnB0dpCxObS9H6FbANVIYNQAu5U4ezd8',
    appId: '1:710172613282:web:6ad770e64ad95c008fd5fb',
    messagingSenderId: '710172613282',
    projectId: 'technq-dev',
    authDomain: 'technq-dev.firebaseapp.com',
    storageBucket: 'technq-dev.firebasestorage.app',
    measurementId: 'G-BCKE2HC6Y0',
  );
}
