// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCRGG-D1Jd0jOGHLzDCWfPT5MPsgoDhgA',
    appId: '1:719499200002:web:bd91739d1508dcad1ec91b',
    messagingSenderId: '719499200002',
    projectId: 'technq-4d7a9',
    authDomain: 'technq-4d7a9.firebaseapp.com',
    storageBucket: 'technq-4d7a9.firebasestorage.app',
    measurementId: 'G-L998FH66N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo2KzjWx3jPbIcK2p0Z4dJbHh1sV5itZE',
    appId: '1:719499200002:android:6e4656f67a7e1e441ec91b',
    messagingSenderId: '719499200002',
    projectId: 'technq-4d7a9',
    storageBucket: 'technq-4d7a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCryN3B_J7SjJS2wpFXImztACMJGvYkEy4',
    appId: '1:719499200002:ios:a668d5283065eaff1ec91b',
    messagingSenderId: '719499200002',
    projectId: 'technq-4d7a9',
    storageBucket: 'technq-4d7a9.firebasestorage.app',
    iosBundleId: 'com.spk.ahp.technq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCryN3B_J7SjJS2wpFXImztACMJGvYkEy4',
    appId: '1:719499200002:ios:a668d5283065eaff1ec91b',
    messagingSenderId: '719499200002',
    projectId: 'technq-4d7a9',
    storageBucket: 'technq-4d7a9.firebasestorage.app',
    iosBundleId: 'com.spk.ahp.technq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCRGG-D1Jd0jOGHLzDCWfPT5MPsgoDhgA',
    appId: '1:719499200002:web:363dd0231afd3eae1ec91b',
    messagingSenderId: '719499200002',
    projectId: 'technq-4d7a9',
    authDomain: 'technq-4d7a9.firebaseapp.com',
    storageBucket: 'technq-4d7a9.firebasestorage.app',
    measurementId: 'G-GTCYNS3N0P',
  );
}
